### ISSUE TITLE
Make a Nix package for formatting Rust code

### ISSUE THREAD

**Issue by soywod** [pimalaya/core#4]
Here the following rustfmt config Pimalaya needs:

```toml
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Horizontal"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
```

Problem: these options are not stable yet, and requires nightly version of Rust, which is not compatible with the stable one the codebase needs).

Need to write down a Nix task that runs rustfmt with the following config on a nightly build of Rust.
